apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ENV: "development"
  HTTP_PORT: "8080"
  HTTP_ALLOWED_ORIGINS: "*"
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE: "orders"
  AWS_ENDPOINT_URL: "http://COMPOSE_HOST:4566"
  ORDERS_TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:orders-events-topic"
  SQS_CATALOG_EVENTS_URL: "http://COMPOSE_HOST:4566/000000000000/orders-catalog-events-queue"
  SQS_PAYMENT_EVENTS_URL: "http://COMPOSE_HOST:4566/000000000000/orders-payment-events-queue"
  USERS_BASE_URL: "http://COMPOSE_HOST:8081"
  STOCK_BASE_URL: "http://COMPOSE_HOST:8082"
  HTTP_CLIENT_TIMEOUT_MS: "2000"
  PUBLIC_BASE_URL: "http://localhost"
  DD_SERVICE: "tech-challenge-orders-api"
  DD_SITE: "datadoghq.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
